### ISSUE TITLE
bug: documentation mismatch between README and Wiki

### ISSUE THREAD

**Issue by lackovic** [nvim-java/nvim-java#289]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Ubuntu 22.04.4 LTS

### Describe the bug

There is one line in the README to install nvim-java (see [here](https://github.com/nvim-java/nvim-java/blob/b3174e41ab51867123d8663eced53b33f1548522/README.md?plain=1#L59-L65)) while in the Wiki there are many lines (see [here](https://github.com/nvim-java/nvim-java/wiki/Lazyvim)). 

Another problem is that the README does not say where to add the line for the installation.

### Steps To Reproduce

1. open the README and read the instructions to install
2. open the Wiki and read the instructions to install

### Expected Behavior

1. The instructions are consistent.
2. The README says where to paste the line.

**Comment by s1n7ax** [comment]
Fixed by
https://github.com/nvim-java/nvim-java/pull/335

**Comment by lackovic** [comment]
> The instructions are consistent.

I still see two different instructions, in the README:

```lua
return {'nvim-java/nvim-java'}
``` 

and in the wiki:

```lua
return {
  'nvim-java/nvim-java',
  config = false,
  dependencies = {
    {
      'neovim/nvim-lspconfig',
      opts = {
        servers = {
          jdtls = {
            -- Your custom jdtls settings goes here
          },
        },
        setup = {
          jdtls = function()
            require('java').setup({
              -- Your custom nvim-java configuration goes here
            })
          end,
        },
      },
    },
  },
}
``` 

> The README says where to paste the line.

The README does not specify where to paste the line.

**Comment by s1n7ax** [comment]
@lackovic In the read me, it shows how to add nvim-java for custom setup. If you don't know where to put it, then you should learn about the package manager first. In wiki, it shows instruction for Lazyvim distribution.

**Comment by lackovic** [comment]
@s1n7ax in your previous message you wrote that you fixed the problems I reported. I simply pointed out that you did not fix them. What did you fix?

**Comment by s1n7ax** [comment]
Doesn't matter. Nothing to be fixed
